# Generated by Django 3.1 on 2020-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paid', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date_paid'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Expense category',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Incomes',
                'ordering': ['-date_received'],
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Income category',
            },
        ),
    ]
